services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    networks:
      - fastapi-network
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    networks:
      - fastapi-network
networks:
  fastapi-network:
    driver: bridge
